# We need to build a custom image including the PHP scripts

name: Build Docker PHP image with flarm scripts

on:
  schedule:
  # Run at 00:00 on day 1 of the month automatically so we are on a semi-latest version of the official PHP base image
  - cron: "0 0 1 * *"
# Allows for manual trigger too in the Github Actions user interface (on github.com, Actions tab)
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Git clone the repository
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}
        
    # Set up the emulator
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create custom buildx builder
      run: docker buildx create --name mybuilder
      
    - name: Use the created builder
      run: docker buildx use mybuilder
    
    - name: Bootstrap builder bootstrap
      run: docker buildx inspect --bootstrap

    - name: Build and push image
      run: docker buildx build --platform=linux/arm64/v8,linux/amd64 -f ./Dockerfile -t ${{ secrets.USERNAME }}/flarm:latest --push .
